PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE files(id INTEGER PRIMARY KEY AUTOINCREMENT, filename TEXT, title TEXT, description TEXT, whichDay INTEGER, lecOrPrac TEXT, forWho TEXT);
COMMIT;
