PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE users(id INTEGER PRIMARY KEY AUTOINCREMENT, usertype TEXT, username TEXT, password TEXT, register_date DATETIME DEFAULT CURRENT_TIMESTAMP);
COMMIT;
