"""empty message

Revision ID: 79845564aa14
Revises: 9e75bcfb1e93
Create Date: 2018-08-15 15:50:28.263486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79845564aa14'
down_revision = '9e75bcfb1e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop', sa.String(), nullable=True),
    sa.Column('parent', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folders')
    # ### end Alembic commands ###
